### PR TITLE
chore(bump mathlib)

### PR DESCRIPTION
**Pull request by spolu**
@jasonrute running in some issues after bumping:

```
=============================================                                               
Change lean path to _target/deps/lean/library
=============================================
Path changed                                 
Insert tactic tracing code                                 
Traceback (most recent call last):                   
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)                                
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)                            
  File "/root/code/formal/formal/lean/lean_proof_recording/lean_proof_recording/pipeline/insert_proof_recording_code.py", line 443, in <module>
    main()                                                                                                  
  File "/root/code/formal/formal/lean/lean_proof_recording/lean_proof_recording/pipeline/insert_proof_recording_code.py", line 429, in main
    insert_tactic_tracing_code(dryrun=dryrun, sexp=sexp)
  File "/root/code/formal/formal/lean/lean_proof_recording/lean_proof_recording/pipeline/insert_proof_recording_code.py", line 79, in insert_tactic_tracing_code
    l1, l2 = find_code_location(TACTIC_LEAN_FILE, ISTEP_CODE)              
  File "/root/code/formal/formal/lean/lean_proof_recording/lean_proof_recording/pipeline/insert_proof_recording_code.py", line 60, in find_code_location
    f"Cannot find an exact instance of the below code in the file {file}:\n{code_string}"
Exception: Cannot find an exact instance of the below code in the file _target/deps/lean/library/init/meta/tactic.lean:
meta def istep {α : Type u} (line0 col0 : ℕ) (line col : ℕ) (t : tactic α) : tactic unit :=
λ s, (@scope_trace _ line col (λ _, step t s)).clamp_pos line0 line col
```

Then builds takes place but nothing is outputted, should be an easy fix?

### CODE REVIEW

**Comment by jasonrute** [comment]
So Mario just [committed his own proof recording code to Lean](https://github.com/leanprover-community/lean/commit/e4203af8b09450ceebc3b44f767e37a96ef47402).  He has code which converts Lean 3 into a large AST which is then automatically translated into Lean 4.  This is part of the Lean 3 to Lean 4 conversion.  (Unfortunately, it doesn't record end positions, so it isn't something directly useful to us.) 

Because he is mucking around with the same code as this repo, the part that edits the deep down lean tactic code can't find the part to edit.  Hopefully, it is a simple fix.  Let me check...

**Comment by jasonrute** [comment]
I modified your PR.  I think it works now, but I didn't get to fully test it before going to bed.

**Comment by spolu** [comment]
Fantastic! Let me try that right waway.

**Comment by spolu** [comment]
Chatted a bit with mario, looks like end pos was eventually added here https://github.com/leanprover-community/lean/pull/614

Should we investigate using the AST export as a source of data?

**Comment by spolu** [comment]
Here: https://github.com/leanprover-community/lean/pull/612

**Comment by spolu** [comment]
Confirmed that it works end to end 👍

**Pull request merged**
